### ISSUE TITLE
Mejora Clase settings

### ISSUE THREAD

**Issue by valenfei05** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sniesdos#9]
- Falta declarar las variables tipo Settings::
-  Declarar bien las variables tipo static
- Incluir `using std::ifstream; using::std::stringstream; using std::invalid_argument` dentro del archivo .h

**Comment by sguevaraidarraga** [comment]
Se arreglo la declaracion de variables de la clase settings settings en su branch y se arreglaron los using en la rama del gestor.
